# Generated by Django 3.2.7 on 2021-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(default='no-imagen.png', null=True, upload_to='', verbose_name='Fotografía')),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['-fecharegistro'],
            },
        ),
    ]
